version: '3.8'
services:
  avalieaqui-app:
    container_name: 'avalieaqui-app'
    image: 'avalieaqui-app'
    build:
      context: ./frontend/avalie_aqui
    env_file:
      - ./frontend/avalie_aqui/src/docker.env
    entrypoint: ['npm', 'run', 'start']
    ports:
      - 3080:3000
    networks:
      - avalieaqui-network
    volumes:
      - ./frontend/avalie_aqui:/app
    depends_on:
      - avalieaqui-api
    pull_policy: build
    restart: unless-stopped

  avalieaqui-api:
    container_name: 'avalieaqui-api'
    image: 'avalieaqui-api'
    build:
      context: ./backend/avalie-aqui
    env_file:
      - ./backend/avalie-aqui/docker.env
    entrypoint: ['./wait-for-postgres.sh', 'npm', 'run', 'start']
    ports:
      - 4000:4000
    networks:
      - avalieaqui-network
    volumes:
      - ./backend/avalie-aqui:/app
    depends_on:
      - postgres-avalieaqui
    pull_policy: build
    restart: unless-stopped

  postgres-avalieaqui:
    container_name: postgres-avalieaqui
    image: postgres:latest
    networks:
      - avalieaqui-network
    environment:
      POSTGRES_PASSWORD: avalieaqui
      POSTGRES_USER: avalieaqui
      POSTGRES_DB: avalieaqui
    volumes:
      - './pgdata:/var/lib/postgresql/data'

networks:
  avalieaqui-network:
    driver: bridge
