version: '3.8'
services:
  api:
    container_name: "avalieaqui_api"
    image: "avalieaqui_api"
    build:
      context: .
    entrypoint: ["./wait-for-postgres.sh", "npm", "run", "start:prod"]
    ports:
      - 4000:4000
    networks:
      - avalieaqui-network
    volumes:
      - ./:/app
    depends_on:
      - postgres-avalieaqui
    restart: unless-stopped

  postgres-avalieaqui:
    container_name: postgres-avalieaqui
    image: postgres:latest
    networks:
      - avalieaqui-network
    environment:
      POSTGRES_PASSWORD: avalieaqui
      POSTGRES_USER: avalieaqui
      POSTGRES_DB: avalieaqui
    ports:
      - 5433:5432
    volumes:
      - "./pgdata:/var/lib/postgresql/data"

networks:
  avalieaqui-network:
    driver: bridge