version: '3.8'
services:
  app:
    container_name: 'avalieaqui-app'
    image: 'avalieaqui-app'
    build:
      context: .
    env_file:
      - ./src/.env.end
    entrypoint: ['npm', 'run', 'start:prod']
    ports:
      - 3000:3000
    volumes:
      - .:/app
    restart: unless-stopped
